package:
  name: Catch2
  version: "3.13.0"
  epoch: 1
  description: "A modern, C++-native, test framework"
  copyright:
    - license: 'BSL-1.0'

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/catchorg/Catch2
      tag: v${{package.version}}
      expected-commit: 29c9844f688acb27c87338c39cd186ebfe41aa19

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: Catch2-static
    description: "A modern, C++-native, test framework - static libraries"
    pipeline:
      - uses: split/static
    test:
      pipeline:
        - uses: test/tw/staticpackage

  - name: Catch2-dev
    description: "A modern, C++-native, test framework - development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/Catch2 "${{targets.subpkgdir}}"/usr/share/
    test:
      pipeline:
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check

update:
  enabled: true
  github:
    identifier: catchorg/Catch2
    strip-prefix: v
