package:
  name: gawk
  version: "5.4.0"
  epoch: 0
  description: "GNU awk pattern-matching language"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://ftpmirror.gnu.org/gnu/gawk/gawk-${{package.version}}.tar.gz
      expected-sha256: df5756d50772212a8e3f26d903107ece3773c4037c6a9e0a59c2a0a8d7329f0d

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: ${{package.name}} manpages
    test:
      pipeline:
        - uses: test/docs

  - name: ${{package.name}}-lang
    pipeline:
      - uses: split/locales
    description: ${{package.name}} locales

update:
  enabled: true
  release-monitor:
    identifier: 868

test:
  pipeline:
    - runs: |
        awk --version
        gawk --version
        gawk-${{package.version}} --version
        gawkbug --version
        awk --help
        gawk --help
        gawk-${{package.version}} --help
        gawkbug --help
    - uses: test/tw/ldd-check
