package:
  name: gh
  version: "2.87.2"
  epoch: 0 # CVE-2025-61732
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6c3e39ffc481d5b9675451a201ae904b6d42c7cd
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

subpackages:
  - name: gh-doc
    description: gh docs
    pipeline:
      - uses: split/alldocs
    test:
      pipeline:
        - uses: test/tw/docs

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        gh --version
        gh --help
