package:
  name: libcap-ng
  version: "0.9.1"
  epoch: 1
  description: POSIX capabilities library
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stevegrubb/libcap-ng.git
      tag: v${{package.version}}
      expected-commit: 427ed6d2c2b16e9b48f12953e55febfead3ef2e2

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --mandir=/usr/share/man \
            --infodir=/usr/share/info \
            --without-python \
            --without-python3 \
            --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - range: ""
    name: libcap-ng-static
    pipeline:
      - uses: split/static
    description: libcap-ng static

  # Move utils before split/dev since split/dev also moves usr/bin
  - range: ""
    name: libcap-ng-utils
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv "${{targets.destdir}}"/usr/bin/* "${{targets.subpkgdir}}/usr/bin/"
    description: posix capabilities utils
    test:
      pipeline:
        - runs: |
            stat /usr/bin/filecap
            stat /usr/bin/netcap
            stat /usr/bin/pscap

  - range: ""
    name: libcap-ng-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libcap-ng
        - linux-headers
    description: libcap-ng dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - range: ""
    name: libcap-ng-doc
    pipeline:
      - uses: split/manpages
    description: libcap-ng manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: stevegrubb/libcap-ng
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/no-docs
