package:
  name: linkerd-await
  version: "0.3.2"
  epoch: 0 # GHSA-434x-w66g-qw3r
  description: "A program that blocks on linkerd readiness"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/linkerd/linkerd-await
      tag: release/v${{package.version}}
      expected-commit: b23359a47ad0156599f59268138bae587fb930e5

  - uses: rust/cargobump

  - name: build linkerd-await
    uses: cargo/build
    with:
      modroot: .
      output: linkerd-await
      install-dir: lib/linkerd

  - uses: strip

update:
  enabled: true
  github:
    identifier: linkerd/linkerd-await
    strip-prefix: release/v

test:
  pipeline:
    - runs: |
        /usr/lib/linkerd/linkerd-await --version | grep ${{package.version}}
