package:
  name: py3-annotated-doc
  version: "0.0.4"
  epoch: 3 # go/wolfi-rsc/py3-annotated-doc
  description: Document parameters, class attributes, return types, and variables inline, with Annotated
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 3Gi

vars:
  pypi-package: annotated-doc
  import: annotated_doc

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - busybox
      - py3-supported-build-base
      - py3-supported-pdm-backend

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fastapi/annotated-doc
      tag: ${{package.version}}
      expected-commit: a6b2d3869f24c9c04cd7c024e59ccec3e5422a56

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
          with:
            python: python${{range.key}}
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: fastapi/annotated-doc
