package:
  name: valijson
  version: "1.1.0"
  epoch: 0 # go/wolfi-rsc/valijson
  description: "C++ library for validating JSON schema"
  copyright:
    - license: "BSD-2-Clause"
  resources:
    cpu: "2"
    memory: 6Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tristanpenman/valijson.git
      tag: v${{package.version}}
      expected-commit: b12841e3fa23a8cc477179face0a5ce5f80b64ab

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: valijson-dev
    description: "C++ library for validating JSON - development headers"
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/header-check
          with:
            files: |
              valijson/constraint_builder.hpp
              valijson/exceptions.hpp
              valijson/schema.hpp
              valijson/schema_cache.hpp
              valijson/schema_parser.hpp
              valijson/subschema.hpp
              valijson/validation_results.hpp
              valijson/validation_visitor.hpp
              valijson/validator.hpp
              valijson/adapters/std_string_adapter.hpp
              valijson/constraints/basic_constraint.hpp
              valijson/constraints/concrete_constraints.hpp
              valijson/constraints/constraint.hpp
              valijson/constraints/constraint_visitor.hpp
              valijson/internal/basic_adapter.hpp
              valijson/internal/debug.hpp
              valijson/internal/json_reference.hpp
              valijson/internal/uri.hpp
              valijson/utils/file_utils.hpp
              valijson/utils/utf8_utils.hpp

update:
  enabled: true
  github:
    identifier: tristanpenman/valijson
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
